import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
import { BrandingSF_Font } from "@/lib/font";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Open Note",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <title>Open Note</title>
        {/* Meta Tags for SEO and responsiveness */}
        <meta
          name="description"
          content="Take notes, stay organized, and collaborate with ease using Open Note."
        />
        <meta name="author" content="Your Name or Your Company" />
        <meta
          name="keywords"
          content="notes, organize, collaborate, productivity, Open Note"
        />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta charSet="UTF-8" />
        {/* Open Graph Meta Tags for social sharing */}
        <meta property="og:title" content="Open Note" />
        <meta
          property="og:description"
          content="Take notes, stay organized, and collaborate with ease."
        />
        <meta property="og:image" content="/images/og-image.jpg" />
        <meta property="og:url" content="https://www.yoursite.com" />
        <meta property="og:type" content="website" />
        {/* Twitter Card Meta Tags for Twitter sharing */}
        <meta name="twitter:card" content="summary_large_image" />
        <meta name="twitter:title" content="Open Note" />
        <meta
          name="twitter:description"
          content="Take notes, stay organized, and collaborate with ease."
        />
        <meta name="twitter:image" content="/images/twitter-card.jpg" />
        {/* Favicon */}
        {/* <link rel="icon" href="/logo.png" sizes="512x512" className="w-20 h-20"/> */}
        <link rel="apple-touch-icon" href="/logo.png" />
        <link rel="icon" type="image/png" sizes="32x32" href="/logo.png" />
        {/* <link rel="icon" type="image/png" sizes="16x16" href="/logo.png" /> */}
        <link rel="manifest" href="/site.webmanifest" />
        {/* Additional Meta Tags */}
        <meta name="robots" content="index, follow" />
        <meta name="google" content="notranslate" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${BrandingSF_Font.className} antialiased bg-[#F7F7F7]`}
      >
        {children}
        <Toaster />
      </body>
    </html>
  );
}
